### 댓글 생성
POST {{local}}/posts/{{postId}}/comments
Content-Type: application/json

{
  "content": "댓글 내용",
  "createdBy": "댓글 작성자"
}

### 댓글 수정
PUT {{local}}/comments/{{commentId}}
Content-Type: application/json

{
  "content": "수정된 댓글 내용",
  "updatedBy": "댓글 수정자"
}

### 댓글 삭제
DELETE {{local}}/comments/{{commentId}}?deletedBy=댓글삭제자
